doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            chat__id:    'App\Chat\Doctrine\IdType'
            chat__email: 'App\Chat\Doctrine\EmailType'
            chat__message_status: 'App\Chat\Doctrine\MessageStatusType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Chat:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Chat/Entity'
                prefix: 'App\Chat\Entity'
                alias: Chat
